import "dotenv/config";
import crypto from "crypto";
import bcrypt from "bcrypt";
import { prisma } from "../lib/prisma";

// Configurable settings via environment variables (with safe operational defaults)
const BASE_FEE = process.env.BOOTSTRAP_BASE_FEE || "500";
const NEW_MEMBER_MULTIPLIER = process.env.BOOTSTRAP_NEW_MEMBER_MULTIPLIER || "2";
const NEW_MEMBER_MONTHS = process.env.BOOTSTRAP_NEW_MEMBER_MONTHS || "3";
const ELIGIBILITY_MONTHS = process.env.BOOTSTRAP_ELIGIBILITY_MONTHS || "3";
const REMOVAL_MONTHS = process.env.BOOTSTRAP_REMOVAL_MONTHS || "3";
const REQUIRE_PAYOUT_APPROVAL = process.env.BOOTSTRAP_REQUIRE_PAYOUT_APPROVAL || "true";

// Settings effective date: set far back (2020-01-01) so all imported historical records fall within validity
const SETTINGS_EFFECTIVE_FROM = new Date(Date.UTC(2020, 0, 1));

function generateSecurePassword(): string {
  return crypto
    .randomBytes(12)
    .toString("base64")
    .replace(/[+/=]/g, "A")
    .slice(0, 16);
}

async function main() {
  console.log("==================================================");
  console.log("🚀 FWCMS Clean Database Bootstrap");
  console.log("==================================================");

  if (!process.env.DATABASE_URL) {
    console.error("❌ ERROR: DATABASE_URL is not set in the environment.");
    console.error("   Please ensure .env has a valid DATABASE_URL.");
    process.exit(1);
  }

  // Display masked connection string for safety
  const maskedUrl = process.env.DATABASE_URL.replace(/:([^:@]+)@/, ":****@");
  console.log(`📡 Target Database: ${maskedUrl}\n`);

  // ---------------------------------------------------------------------------
  // 1. System Settings
  // ---------------------------------------------------------------------------
  console.log("⚙️  1. Seeding core system settings...");
  const settingDefs = [
    { key: "baseFee", value: String(BASE_FEE) },
    { key: "newMemberMultiplier", value: String(NEW_MEMBER_MULTIPLIER) },
    { key: "newMemberMonths", value: String(NEW_MEMBER_MONTHS) },
    { key: "eligibilityMonths", value: String(ELIGIBILITY_MONTHS) },
    { key: "removalMonths", value: String(REMOVAL_MONTHS) },
    { key: "requirePayoutApproval", value: String(REQUIRE_PAYOUT_APPROVAL) },
  ];

  for (const s of settingDefs) {
    await prisma.setting.upsert({
      where: {
        key_effectiveFrom: { key: s.key, effectiveFrom: SETTINGS_EFFECTIVE_FROM },
      },
      update: { value: s.value },
      create: { ...s, effectiveFrom: SETTINGS_EFFECTIVE_FROM },
    });
    console.log(`   ✔ ${s.key.padEnd(23)} = ${s.value}`);
  }
  console.log(`   (Effective from: ${SETTINGS_EFFECTIVE_FROM.toISOString().slice(0, 10)})`);

  // ---------------------------------------------------------------------------
  // 2. Office Bearer / User Accounts
  // ---------------------------------------------------------------------------
  // Note: Payments and payouts require foreign key references to recordedById,
  // requestedById, vpDecisionById, and presDecisionById. We create the standard roles:
  // admin, treasurer, vp, president, and data_entry.
  console.log("\n👥 2. Seeding initial office-bearer accounts...");

  const adminEmail = (process.env.BOOTSTRAP_ADMIN_EMAIL || "admin@fwc.local").trim().toLowerCase();
  const adminPassword = process.env.BOOTSTRAP_ADMIN_PASSWORD || generateSecurePassword();

  const userConfigs = [
    {
      role: "admin" as const,
      email: adminEmail,
      name: process.env.BOOTSTRAP_ADMIN_NAME || "System Administrator",
      password: adminPassword,
      isAutoGenerated: !process.env.BOOTSTRAP_ADMIN_PASSWORD,
    },
    {
      role: "treasurer" as const,
      email: (process.env.BOOTSTRAP_TREASURER_EMAIL || "treasurer@fwc.local").trim().toLowerCase(),
      name: process.env.BOOTSTRAP_TREASURER_NAME || "Treasurer",
      password: process.env.BOOTSTRAP_TREASURER_PASSWORD || generateSecurePassword(),
      isAutoGenerated: !process.env.BOOTSTRAP_TREASURER_PASSWORD,
    },
    {
      role: "vp" as const,
      email: (process.env.BOOTSTRAP_VP_EMAIL || "vp@fwc.local").trim().toLowerCase(),
      name: process.env.BOOTSTRAP_VP_NAME || "Vice President",
      password: process.env.BOOTSTRAP_VP_PASSWORD || generateSecurePassword(),
      isAutoGenerated: !process.env.BOOTSTRAP_VP_PASSWORD,
    },
    {
      role: "president" as const,
      email: (process.env.BOOTSTRAP_PRESIDENT_EMAIL || "president@fwc.local").trim().toLowerCase(),
      name: process.env.BOOTSTRAP_PRESIDENT_NAME || "President",
      password: process.env.BOOTSTRAP_PRESIDENT_PASSWORD || generateSecurePassword(),
      isAutoGenerated: !process.env.BOOTSTRAP_PRESIDENT_PASSWORD,
    },
    {
      role: "data_entry" as const,
      email: (process.env.BOOTSTRAP_DATAENTRY_EMAIL || "dataentry@fwc.local").trim().toLowerCase(),
      name: process.env.BOOTSTRAP_DATAENTRY_NAME || "Data Entry Operator",
      password: process.env.BOOTSTRAP_DATAENTRY_PASSWORD || generateSecurePassword(),
      isAutoGenerated: !process.env.BOOTSTRAP_DATAENTRY_PASSWORD,
    },
  ];

  const credentialsLog: Array<{ role: string; email: string; password: string; isNew: boolean }> = [];

  for (const u of userConfigs) {
    const existing = await prisma.user.findUnique({ where: { email: u.email } });
    const hashedPassword = await bcrypt.hash(u.password, 10);

    if (existing) {
      // Update role and name; only update password if explicitly provided via env
      const shouldUpdatePassword = !u.isAutoGenerated;
      await prisma.user.update({
        where: { email: u.email },
        data: {
          name: u.name,
          role: u.role,
          ...(shouldUpdatePassword ? { password: hashedPassword } : {}),
        },
      });
      console.log(`   ✔ Updated existing user: ${u.email} (${u.role})`);
    } else {
      await prisma.user.create({
        data: {
          email: u.email,
          name: u.name,
          role: u.role,
          password: hashedPassword,
        },
      });
      console.log(`   ✔ Created new user:      ${u.email} (${u.role})`);
      credentialsLog.push({
        role: u.role,
        email: u.email,
        password: u.password,
        isNew: true,
      });
    }
  }

  // If new accounts were created with generated passwords, display them securely
  if (credentialsLog.length > 0) {
    console.log("\n🔐 -------------------------------------------------------------");
    console.log("   NEW USER CREDENTIALS CREATED (SAVE THESE NOW):");
    console.log("----------------------------------------------------------------");
    for (const cred of credentialsLog) {
      console.log(`   Role:     ${cred.role.padEnd(12)}`);
      console.log(`   Email:    ${cred.email}`);
      console.log(`   Password: ${cred.password}`);
      console.log("   -------------------------------------------------------------");
    }
  }

  console.log("\n==================================================");
  console.log("✅ Bootstrap Finished Successfully!");
  console.log("   - Clean state: 0 dummy members, 0 dummy payments.");
  console.log("   - Ready for real data import from fig-accounts.xlsx");
  console.log("==================================================\n");
}

main()
  .catch(async (e) => {
    console.error("\n❌ Bootstrap failed with error:", e);
    await prisma.$disconnect();
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
